---
- name: User management playbook
  hosts: web
  vars:
    usermgmt:
      - username: bob
        type: developer
      - username: john
        type: developer
      - username: bill
        type: analyst
      - username: jane
        type: analyst
    groupmgmt:
      - groupname: web-designer
        gid: 20000
      - groupname: system-analyst
        gid: 30000
