name: Trigger Remote Workflow

on:
  push:
    branches:
    - master

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ansible repo workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'avijkund',
              repo: 'ansible',
              workflow_id: 'blank.yml',
              ref: 'main',
              inputs: {
                env: 'dev'
              }
            })
