# This is a basic workflow to help you get started with Actions

name: Deploy


# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: branch/tag
        required: false
        type: string
      
        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Check:
  #     # The type of runner that the job will run on
  #     runs-on: self-hosted
  #     container:
  #       image: 9831259430/ansiblerepo:v2
  #     steps:
  #       - name: Checkout code
  #         uses: actions/checkout@v3
  #       - name: Run the playbook
  #         run: |
  #           #cp inventory /etc/ansible/hosts
  #           export ANSIBLE_HOST_KEY_CHECKING=False
  #           ansible-playbook -i inventory -u avijit test.yml -C
  deploy:
      # The type of runner that the job will run on
      runs-on: self-hosted
      needs: []      
      container:
        image: 9831259430/ansiblerepo:v2
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        # Runs a set of commands using the runners shell
        - name: Run the playbook
          run: |
            echo "${{ github.event.inputs.my_input }}"
            #cp inventory /etc/ansible/hosts
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i inventory -u avijit test.yml -vvvv > ansible.log

