# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: Linux
    container:
      image: ansible/ansible
    steps:
        # Runs a single command using the runners shell
        - name: Run a one-line script
          run: echo Hello, world!
  test:
      # The type of runner that the job will run on
      runs-on: self-hosted
      needs: [build]
      container:
        image: ansible/ansible
      steps:
        - name: Run the playbook
          run: |
            ansible-playbook test.yml --check
  deploy:
      # The type of runner that the job will run on
      runs-on: self-hosted
      needs: [test]
      container:
        image: ansible/ansible
      steps:
        # Runs a set of commands using the runners shell
        - name: Run the playbook
          run: |
            ansible-playbook test.yml 
